version: "3"

services:
  auth:
    image: auth_service
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    container_name: auth_service
    command: python3 main.py
    env_file: .env
    ports:
      - "${PORT}:8000"
    volumes:
      - .:/workspace
    networks:
      - closed

volumes:
  mongo:

networks:
  closed:
    name: closed
    external: true
