FROM base_user_service

WORKDIR /workspace

COPY ./requirements/requirements.txt /workspace/requirements/requirements.txt
COPY ./app /workspace/app

RUN pip3 install -r ./requirements/requirements.txt

WORKDIR /workspace/app

ENTRYPOINT ["python3", "main.py"]