version: "3"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - closed
  user:
    image: user_service
    build:
      context: .
      dockerfile: docker/dockerfile.dev
    restart: unless-stopped
    container_name: user_service
    env_file: .env
    ports:
      - "${PORT}:8080"
    volumes:
      - .:/workspace
    networks:
      - closed

networks:
  closed:
    ipam:
      driver: default
      config:
        - subnet: "172.168.0.0/24"
