version: "3"

services:
  mongodb:
    image: mongo
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo:/data/db
  user:
    image: base_user_service
    build:
      context: .
      dockerfile: docker/dockerfile.base

volumes:
  mongo:
